name: AWS Lambda Deployment
on:
  push:
    branches:
      - main
jobs:
    Deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build
        #working-directory: ./lambda/${{ secrets.AWS_FUNCTION_NAME }}
        run: |
          go get .
          go env -w CGO_ENABLED=0
          go build -o bootstrap -tags lambda.norpc main.go
          chmod a+x bootstrap
      - name: Zip
        #working-directory: ./lambda/${{ secrets.AWS_FUNCTION_NAME }}
        run: zip -j ${{ secrets.AWS_FUNCTION_NAME }}.zip bootstrap
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload Zip
        #working-directory: ./lambda/${{ secrets.AWS_FUNCTION_NAME }}
        run: aws lambda update-function-code --function-name ${{ secrets.AWS_FUNCTION_NAME }} --zip-file fileb://${{ secrets.AWS_FUNCTION_NAME }}.zip